[tutorial] Advise using `--locked` in `cargo install`
This makes cargo use the lockfile for dependencies. Without that, at the
time of writing this patch, the install fails with the following error:

    error: failed to compile `move-cli v0.1.0 (/home/wiktor/src/open-source/move/language/tools/move-cli)`, intermediate artifacts can be found at `/home/wiktor/tmp/cargo`

    Caused by:
      package `toml_datetime v0.6.5` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.65.0

Alternative solution would be upgrading Rust version but adding `--locked`
to the tutorial is far less invasive.

See: https://github.com/rust-lang/cargo/issues/7169#issuecomment-514361495